"""
Reads every CSV in raw/ (shared schema, see README.md), and pivots into
the team's 4x4 attack x defense matrix. Writes MATRIX.md.

Usage:
  python build_matrix.py
  python build_matrix.py --raw-dir raw --out MATRIX.md
"""
import argparse
import csv
from collections import defaultdict
from pathlib import Path

FIELDS = ["contributor", "attack_method", "defense_method", "model", "task_id",
          "strategy", "condition", "metric_name", "metric_value", "n_samples", "run_id", "notes"]


def load_raw(raw_dir):
    rows = []
    for path in sorted(Path(raw_dir).glob("*.csv")):
        with open(path, newline="") as f:
            for r in csv.DictReader(f):
                missing = [c for c in FIELDS if c not in r]
                if missing:
                    print(f"WARNING: {path.name} missing columns {missing}, skipping file")
                    break
                rows.append(r)
    return rows


def mean(vals):
    vals = [float(v) for v in vals if v not in (None, "")]
    return sum(vals) / len(vals) if vals else None


def build_pivots(rows):
    """
    cells[(attack_method, defense_method)][metric_name][condition] -> list of values
    """
    cells = defaultdict(lambda: defaultdict(lambda: defaultdict(list)))
    for r in rows:
        key = (r["attack_method"], r["defense_method"])
        cells[key][r["metric_name"]][r["condition"]].append(r["metric_value"])
    return cells


def render_pivot_table(cells, attack_methods, defense_methods, metric_name, label):
    lines = [f"### {label}", ""]
    header = "| attack \\ defense | " + " | ".join(defense_methods) + " |"
    sep = "|---" * (len(defense_methods) + 1) + "|"
    lines += [header, sep]
    for am in attack_methods:
        row = [am]
        for dm in defense_methods:
            data = cells.get((am, dm), {}).get(metric_name)
            if not data:
                row.append("—")
                continue
            m_attack = mean(data.get("attack", []))
            m_benign = mean(data.get("benign_control", []))
            if m_attack is None and m_benign is None:
                row.append("—")
            else:
                gap = (m_attack - m_benign) if (m_attack is not None and m_benign is not None) else None
                cell_str = f"atk {m_attack:.2f}" if m_attack is not None else "atk —"
                cell_str += f" / ben {m_benign:.2f}" if m_benign is not None else " / ben —"
                if gap is not None:
                    cell_str += f" (Δ{gap:+.2f})"
                row.append(cell_str)
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--raw-dir", default="raw")
    ap.add_argument("--out", default="MATRIX.md")
    args = ap.parse_args()

    rows = load_raw(args.raw_dir)
    if not rows:
        print(f"No valid rows found in {args.raw_dir}/ -- nothing to build.")
        return

    attack_methods = sorted({r["attack_method"] for r in rows})
    defense_methods = sorted({r["defense_method"] for r in rows})
    contributors = sorted({r["contributor"] for r in rows})
    metric_names = sorted({r["metric_name"] for r in rows})

    print(f"Loaded {len(rows)} rows from {args.raw_dir}/")
    print(f"Attack methods seen ({len(attack_methods)}/4 expected): {attack_methods}")
    print(f"Defense methods seen ({len(defense_methods)}/4 expected): {defense_methods}")
    print(f"Contributors: {contributors}")

    cells = build_pivots(rows)

    out_lines = [
        "# CompJailBench 4x4 Results Matrix",
        "",
        f"Auto-generated by build_matrix.py from {len(rows)} rows across {len(contributors)} contributor(s).",
        f"Attack methods present: {len(attack_methods)}/4. Defense methods present: {len(defense_methods)}/4.",
        "",
        "Each cell shows mean(metric | attack) / mean(metric | benign_control), and the gap (Δ) between them.",
        "Gap is a placeholder signal, not a validated AUROC -- see README.md.",
        "",
    ]
    for metric in metric_names:
        label = f"Metric: {metric}"
        out_lines.append(render_pivot_table(cells, attack_methods, defense_methods, metric, label))

    Path(args.out).write_text("\n".join(out_lines))
    print(f"\nWrote {args.out}")


if __name__ == "__main__":
    main()
